plugins {
    id 'multiloader-loader'

    alias(libs.plugins.loom)
//    alias(libs.plugins.minotaur)
//    alias(libs.plugins.cursegradle)
}

//apply from: 'https://raw.githubusercontent.com/CodinGlitch/gradle-templates/main/repository-publishers/codinglitch.gradle'
//apply from: 'https://raw.githubusercontent.com/CodinGlitch/gradle-templates/main/site-publishers/curseforge.gradle'
//apply from: 'https://raw.githubusercontent.com/CodinGlitch/gradle-templates/main/site-publishers/modrinth.gradle'

dependencies {
    minecraft(libs.fabric.minecraft)

    mappings loom.layered {
        officialMojangMappings()
        parchment("org.parchmentmc.data:parchment-${libs.versions.parchment.minecraft.get()}:${libs.versions.parchment.mappings.get()}@zip")
    }

    modImplementation libs.bundles.fabric.modImpl

    implementation libs.bundles.nightconfig
    include libs.bundles.nightconfig

    modLocalRuntime libs.bundles.fabric.environment
}