# Project
version=1.4.20
group=com.codinglitch.lexiconfig
java_version=17

# 1.18 to 1.20.6
compatibility=epic

# Common
mod_name=Lexiconfig
mod_author=CodinGlitch
mod_id=lexiconfig
license=GNU GPLv3
credits=
description=This is a config API that aims to provide many integrations alongside other libraries, and to be as easy as possible to use, for both developers and users alike.

minecraft_min=1.18
minecraft_max=1.20.6

# Publishing
modrinth_id=D157Rgyf
curseforge_id=1019452

required=
optional=configured

release_type=STABLE
debug_mode=true

# Gradle
org.gradle.jvmargs=-Xmx6G
org.gradle.daemon=false
