# Important Notes:
# Every field you add must be added to the root build.gradle expandProps map.

# Project
version=1.4.17-a
group=com.codinglitch.lexiconfig
java_version=17

# Common
minecraft_version=1.20.4
mod_name=Lexiconfig
mod_author=CodinGlitch
mod_id=lexiconfig
license=GNU GPLv3
credits=
description=This is a config API that aims to provide many integrations alongside other libraries, and to be as easy as possible to use, for both developers and users alike.
minecraft_version_range=[1.16,)

# Fabric
fabric_version=0.97.2+1.20.4
fabric_loader_version=0.16.13
fabric_minecraft_version_range=>=1.16

# Forge
forge_version=49.2.0
forge_version_range=[1,)

# NeoForge
neoforge_version=20.4.77-beta
neoforge_version_range=[1,)

# Environment
config_mod=configured

# Dependencies
night_config_version=3.6.6

# Compatibilities
configured_version=1.20.4-2.2.3

# Publishing
name_template=[_uppercase_loader] Lexiconfig _version
modrinth_id=D157Rgyf
curseforge_id=1019452
supported_versions=1.20.2,1.20.3,1.20.4

requiredDependencies=
optionalDependencies=configured

release_type=release
debug_mode=false

exclude_groups=com.mrcrayfish

# Gradle
org.gradle.jvmargs=-Xmx6G
org.gradle.daemon=false
