[versions]
#---- Common ----#
minecraft           = "1.20.1"

parchment_minecraft = "1.20.1"
parchment_mappings  = "2023.09.03"

#---- Fabric ----#
fabric_api          = "0.92.5+1.20.1"
fabric_loader       = "0.16.10"

#---- Forge ----#
forge               = "1.20.1-47.4.0"
forge_range         = "[1,)"

#---- Plugins ----#
loom                = "1.10-SNAPSHOT"
legacy_forge        = "2.0.141"
idea_ext            = "1.2"

mod_publish         = "2.0.0-beta.2"

#---- Dependencies ----#
mixin               = "0.8.5"
mixin_extras        = "0.4.1"

night_config        = "3.6.6"

#---- Environment ----#
configured          = "1.20.1-2.2.3"


[libraries]
#---- Common ----#
mixin = { group="org.spongepowered", name="mixin", version.ref="mixin" }
mixinextras_common = { group="io.github.llamalad7", name="mixinextras-common", version.ref="mixin_extras" }

nightconfig_core = { group="com.electronwill.night-config", name="core", version.ref="night_config" }
nightconfig_toml = { group="com.electronwill.night-config", name="toml", version.ref="night_config" }

configured = { group="com.mrcrayfish", name="configured-common", version.ref="configured"}

#---- Fabric ----#
fabric = { group="net.fabricmc", name="fabric-loader", version.ref="fabric_loader" }
fabric_api = { group="net.fabricmc.fabric-api", name="fabric-api", version.ref="fabric_api" }

fabric_minecraft = { group="com.mojang", name="minecraft", version.ref="minecraft" }

fabric_configured = { group="com.mrcrayfish", name="configured-fabric", version.ref="configured"}

#---- Forge ----#
forge_configured = { group="com.mrcrayfish", name="configured-forge", version.ref="configured"}


[plugins]
#---- Publishing ----#
modpublish = { id = "me.modmuss50.mod-publish-plugin", version.ref = "mod_publish" }

#---- Loaders ----#
legacyforge = { id = "net.neoforged.moddev.legacyforge", version.ref = "legacy_forge" }
ideaext = { id = "org.jetbrains.gradle.plugin.idea-ext", version.ref = "idea_ext" }
loom = { id = "fabric-loom", version.ref = "loom" }

[bundles]

nightconfig = [ "nightconfig_core", "nightconfig_toml" ]

#---- Fabric ----#
fabric_modImpl = [ "fabric", "fabric_api" ]

# All mods that should be enabled in the Fabric development environment.
fabric_environment = [
    "fabric_configured"
]

#---- NeoForge ----#

# All mods that should be enabled in the NeoForge development environment.
forge_environment = [
    "forge_configured"
]